source "https://rubygems.org"
gemspec
gem "sinatra"
gem "haml"
gem "sass"
gem "opentox-server", :path => "../opentox-server"
gem "opentox-client", :path => "../opentox-client"
gem "opentox-algorithm", :path => "../algorithm"
gem "opentox-compound", :path => "../compound"
gem "opentox-dataset", :path => "../dataset"
gem "opentox-feature", :path => "../feature"
gem "opentox-model", :path => "../model"
gem "opentox-task", :path => "../task"
gem "opentox-validation", :path => "../validation"
