source "https://rubygems.org"
gemspec
gem "lazar", :path => "../lazar"
gem "qsar-report", :path => "../qsar-report"
gem "gem-path"
gem "sinatra"
gem "sinatra-reloader"
gem "haml"
gem "sass"
gem "rdiscount"
